apiVersion: compute.customcomputeprovider.crossplane.io/v1alpha1
kind: Compute
metadata:
  name: compute-cp
spec:
  forProvider:
    awsConfig:
      region: "us-east-1"
    instanceConfig:
      name: "cp-crossplane1"
      type: "t2.micro"
      ami: "ami-05b10e08d247fb927"

      storage:
      - deviceName: "/dev/xvda"
        diskType: "gp3"
        diskSize: 30

      networking:
        subnetID: "subnet-0f3031cfcab95eb28"
        securityGroups:
        - sg-05ae307de29c35433

      tags:
        "Environment": "Dev"
        "Iac": "Crossplane"
        "Fe": "Backstage"
        "GitOps": "ArgoCD"

  providerConfigRef:
    name: example