apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: customcomputeprovider
spec:
  package: public.ecr.aws/v5l8y3e2/upbound/custom-provider-cp:v.0.3.1
  packagePullPolicy: Always
  skipDependencyResolution: true